RecursiveFibonacci Class Reference
The Fibonacci child class, uses a recursive loop to find the fibonacci
Public Member Functions
RecursiveFibonacci (int number)
Contructor for define Number property
RecursiveFibonacci ()
Int64 GetFibonacci ()
Get fibonacci of Number Property using recusivity
Private Member Functions
Int64[] GetFibonacci (Int64 number)
Get fibonacci of Number Property using recusivity
Int64 GetFibonacci2 (Int64 number)
Get fibonacci of Number Property using recusivity
Int64 GetFibonacci3 (Int64 number)
Get fibonacci of Number Property using recusivity
Additional Inherited Members
Detailed Description
The Fibonacci child class, uses a recursive loop to find the fibonacci
Definition at line 69 of file Fibonacci.cs.
Constructor & Destructor Documentation
RecursiveFibonacci() [1/2]
RecursiveFibonacci.RecursiveFibonacci (int number)
Contructor for define Number property
Using Fibonacci Class contructor
Parameters
number upper limit of fibonacci to find
summary> Default constructor
remarks>Using Fibonacci Class contructor
Definition at line 74 of file Fibonacci.cs.
RecursiveFibonacci() [2/2]
RecursiveFibonacci.RecursiveFibonacci ()
Definition at line 77 of file Fibonacci.cs.
Member Function Documentation
GetFibonacci() [1/2]
Int64 RecursiveFibonacci.GetFibonacci ()
Get fibonacci of Number Property using recusivity
The Time property is equal to the delay time, use other Method
Returns
Fibonacci of Number
Definition at line 82 of file Fibonacci.cs.
References GetFibonacci(), Fibonacci.Number, and Fibonacci.Time.
GetFibonacci() [2/2]
Int64[] RecursiveFibonacci.GetFibonacci (Int64 number) [private]
Get fibonacci of Number Property using recusivity
Parameters
number number of fibonacci to find
Returns
Fibonacci of Number
Definition at line 100 of file Fibonacci.cs.
References GetFibonacci().
GetFibonacci2()
Int64 RecursiveFibonacci.GetFibonacci2 (Int64 number) [private]
Get fibonacci of Number Property using recusivity
Parameters
number number of fibonacci to find
Returns
Fibonacci of Number
Definition at line 112 of file Fibonacci.cs.
References GetFibonacci2().
GetFibonacci3()
Int64 RecursiveFibonacci.GetFibonacci3 (Int64 number) [private]
Get fibonacci of Number Property using recusivity
Parameters
number number of fibonacci to find
Returns
Fibonacci of Number
Definition at line 121 of file Fibonacci.cs.
References GetFibonacci3().
The documentation for this class was generated from the following file:
Fibonacci.cs